config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :loans

  get 'authentications/index'

  resources :items

  resources :users
  resources :borrowers

  resources :sessions, only: [:new, :create, :destroy]

  resources :authentications

  # Login information
  match '/register', to: "users#new", via: 'get'
  match '/login', to: 'sessions#new', via: 'get'
  match '/logout', to: 'sessions#destroy', via: 'delete'

  # Login Information
  #match '/settings/user'

  # OmniAuth Routes
  match 'auth/:provider/callback', to: 'authentications#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]

  root :to => "visitors#index"

  mount Sidekiq::Web, at: "/sidekiq"

end

app/models/loan.rb
class Loan < ActiveRecord::Base
  belongs_to :lender, class_name: "User"
  belongs_to :borrower, class_name: "Borrower"
  belongs_to :item


  has_many :loan_reminders

  after_create :build_reminder, if: -> {self.email_me?}
  after_update :destroy_reminder, if: -> {!self.email_me?}


  validates :item, presence: true
  validates :borrower, presence: true

  validates_associated :item
  validates_associated :borrower

  def item_attributes= p
    build_item p.merge( user: lender )
  end

  def borrower_attributes= p
    build_borrower p.merge( user: lender)
  end

  private
    def build_reminder
      self.loan_reminders.create(user_id: self.lender_id, send_date: self.return_by)
    end

    def destroy_reminder
      self.loan_reminders.destroy
    end
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  before_action :signed_in_user, only: [:create, :edit, :update, :destroy]

  def new
    redirect_to root_url, alert: "Please Login" unless signed_in?
    @loan = Loan.new
  end


  def edit
    @loan = current_user.loans.find(params[:id])
  end

  def update
    @loan = current_user.loans.find(params[:id])
  end

  def destroy
    @loan  = Loan.find(params[:id])
    @loan.destroy

    flash[:success] = "Loan successfully removed!"

    redirect_to root_url
  end

  def create
    @loan = current_user.loans.build
    @loan.attributes = loan_params

    if @loan.save
      unless @loan.return_by.nil?
        UserMailer.delay_until(@loan.return_by.to_time(:utc)).loan_email(current_user.id, @loan.id)
      end

      flash[:success] = "Loan Created!"
      redirect_to root_url
    else
      render 'loans/new'
    end
  end

  private
    def loan_params
      params.require(:loan).permit(:loaned_on, :return_by, :unknown_date, :unknown_loan_date, :return_whenever, :email_me,
                                   borrower_attributes: [ :name ], item_attributes: [ :name, :image ])
    end
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/views/loans/_form.html.erb
  <h1>Create New Loan Form here</h1>
    <h3>Parameters for Loan Form (nested forms)</h3>
    <ul>
      <li>New/Existing Item Form, should have item name, specify a picture to upload</li>
      <li>New/Existing Borrower Form, borrower name (autocomplete with Facebook friends name and the likes)</li>
      <li>Date of Loan (add a checkbox for unknown)</li>
      <li>Requested Return Date (add a checkbox for indeterminate/whenever)</li>
      <li>If there is a requested return date, then show a checkbox for an e-mail reminder.</li>
      <li>No requested return date? Then the checkbox should state, "E-mail me in N [days, weeks,months] from [today, loan date]</li>
      <li>And Submit Button</li>
  </ul>

<div class="col-md-6 col-md-offset-3">
  <%= bootstrap_form_for @loan, :multipart => true do |f| %>
    <%= render 'shared/error_messages', object: f.object %>


    <% f.fields_for :borrower_attributes do |b| %>
        <%= b.text_field :name, label: "Borrower's Name" %>
    <% end %>

    <% f.fields_for :item_attributes do |i| %>
      <%= i.text_field :name, label: "Item Name" %>
      <%= i.file_field :image, label: "Picture of Item (Optional)" %>
      <%= i.text_field :image_url, label: "Upload from URL . . . " %>
    <% end %>


    <div class="row">
      <div class="col-md-6">
        <%= f.date_field :loaned_on, :value => Time.zone.today-1, max: Time.zone.today %>
        <%= f.check_box :unknown_loan_date, label: "I Don't Remember" %>
      </div>

      <div class="col-md-6">
        <%= f.date_field :return_by, min: Time.zone.today, value: Time.zone.today+14 %>
        <%= f.check_box :return_whenever, label: "Doesn't matter, return whenever" %>
      </div>
    </div>

    <%= f.check_box :email_me, label: "Send me an email reminding me that the item is due" %>

    <%= f.submit "Create New Loan", class: "btn btn-primary" %>
  <% end %>

</div>

app/views/loans/_user_loan_list.html.erb
    <div class="col-md-7 col-md-offset-1">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h4>User Inventory</h4>
        </div>

        <%= link_to "<i class='fa fa-plus-circle fa-fw'></i> Add New Loan".html_safe, new_loan_url, class: "btn btn-success btn-block custom-btn" %>

        <ul class="loans list-group">
          <% current_user.loans.each do |loan| %>
            <li class="list-group-item">
              <div class="row custom-row">

                <div class="col-md-4">
                  <%= image_tag loan.item.image.url, class: "img-square custom-img" %>
                </div>
                <div class="col-md-7 loan-info">
                  <h4><%= loan.item.name %></h4>
                  <h5>Borrowed by <%= loan.borrower.name %></h5>

                  <% if loan.return_by.past? %>
                    <h6>Item due <%= time_ago_in_words(loan.return_by) %> ago</h6>
                  <% else %>
                    <h6>Item due in <%= time_ago_in_words(loan.return_by) %></h6>
                  <% end %>

                  <div class="pull-right">
                    <%= link_to '<i class="fa fa-pencil fa-fw"></i> Edit'.html_safe, edit_loan_path(loan), class: "" %>
                    <%= link_to '<i class="fa fa-trash-o fa-fw"></i> Delete'.html_safe, loan_path(loan), method: :delete, remote: true,
                    data: { confirm: 'Are you sure?' }, class: "" %>
                  </div>


                </div>

              </div>
            </li>

          <% end %>
        </ul>

      </div>

    </div>

app/views/loans/edit.html.erb
<div class="col-md-6 col-md-offset-3">

  <h1>Edit Loan</h1>
  <%= bootstrap_form_for @loan, action: :update,  id: @loan.id do |f|  %>
    <%= render 'shared/error_messages', object: f.object %>

    <%= f.fields_for :borrower_attributes do |b| %>
      <%= b.text_field :name, label: "Borrower Name", value: @loan.borrower.name %>
    <% end %>

    <%= f.fields_for :item_attributes do |i| %>
      <%= i.text_field :name, label: "Item Name", value: @loan.item.name %>
    <% end %>

    <div class="row">
      <div class="col-md-6">
        <%= f.date_field :loaned_on, :value => @loan.loaned_on, max: Time.zone.today %>
        <%= f.check_box :unknown_loan_date, label: "I Don't Remember" %>
      </div>

      <div class="col-md-6">
        <%= f.date_field :return_by, min: Time.zone.today, value: @loan.return_by %>
        <%= f.check_box :return_whenever, label: "Doesn't matter, return whenever" %>
      </div>
    </div>

    <%= f.check_box :email_me, label: "Send me an email reminding me that the item is due" %>

    <%= f.submit "Create New Loan", class: "btn btn-primary" %>

  <% end %>
</div>

app/views/loans/new.html.erb
<%= render 'form' %>