config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :loans

  get 'authentications/index'

  resources :items

  resources :users
  resources :borrowers

  resources :sessions, only: [:new, :create, :destroy]

  resources :authentications

  # Login information
  match '/register', to: "users#new", via: 'get'
  match '/login', to: 'sessions#new', via: 'get'
  match '/logout', to: 'sessions#destroy', via: 'delete'

  # Login Information
  #match '/settings/user'

  # OmniAuth Routes
  match 'auth/:provider/callback', to: 'authentications#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]

  root :to => "visitors#index"

  mount Sidekiq::Web, at: "/sidekiq"

end

app/models/item.rb
require 'open-uri'

class Item < ActiveRecord::Base
  has_attached_file :image, :styles => { :medium => "300x300", :thumb => "100x100", :portrait => "125x125" }, :default_url => "http://placehold.it/100x125"
  belongs_to :category
  belongs_to :user
  default_scope -> { order('name ASC') }

  has_many :loans, :foreign_key => "item_id"
  has_many :borrowers, :through => :loans



  # Image URL virtual attribute for remote uploads
  attr_accessor :image_url

  before_validation :download_remote_image, :if => :image_url_provided?
  validates_presence_of :image_remote_url, :if => :image_url_provided?, :message => "is invalid or inaccessible"

  validates :name, presence: true
  validates :user_id, presence: true

  # Image Validation
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  validates_attachment_file_name :image, :matches => [/png\Z/, /jpe?g\Z/, /jpg\Z/]


  private
  # Image download functions found from this Gist, https://gist.github.com/jgv/1502777
  def image_url_provided?
    !self.image_url.blank?
  end

  def download_remote_image
    puts "Downloading remote image . . ."
    io = open(URI.parse(self.image_url))
    self.image = URI.parse(self.image_url)
    self.image_remote_url = image_url
  rescue # catch url errors with validations instead of exceptions (Errno::ENOENT, OpenURI::HTTPError, etc...)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :signed_in_user, only: [:index, :create, :destroy]

  def index
    @items = current_user.items
  end

  def new
    redirect_to root_url, alert: "Please login" unless signed_in?

    @item = Item.new
  end

  def edit
    @item = current_user.items.find(params[:id])
  end

  def update
    @item = current_user.items.find(params[:id])
  end

  def create
    @item = current_user.items.build(item_params)
    if @item.save
      flash[:success] = "Item successfully created!"
      redirect_to items_path
    else
      render 'new'
    end
  end

  def destroy
    @item = current_user.items.find(params[:id])
    @item.destroy
    flash[:success] = "Item successfully destroyed!"
    redirect_to items_path
  end

  private
    def item_params
      params.require(:item).permit(:name, :image, :image_url)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<div class="col-md-6 col-md-offset-3">
  <h1>Edit Item</h1>
  <%= bootstrap_form_for @item do |f| %>

  <% end %>
</div>

app/views/items/index.html.erb
<div class="col-md-8 col-md-offset-2">
  <div class="row">

    <div class="page-header">
            <h1>Your Inventory <%= link_to "<i class='fa fa-plus-circle fa-fw'></i> Add Item".html_safe, new_item_path, class: "btn btn-success pull-right custom-btn" %></h1>

    </div>



    <% if @items.empty? %>
      <h4>You don't have any items in your inventory yet, why don't you <%= link_to "add", new_item_path %> one?</h4>
    <% else %>
      <div class="row">

      <% @items.each do |item| %>
          <div class="col-md-3">
              <%= image_tag item.image.url(:portrait), class: "pull-left" %>
              <h4 class="clear-left item-details"><%= item.name %></h4>


              <div class="pull-left">
              <%= link_to '<i class="fa fa-pencil"></i> Edit'.html_safe, edit_item_path(item) %>

              <%= link_to '<i class="fa fa-trash-o"></i> Delete'.html_safe, item_path(item), method: :delete,
                data: { confirm: 'Are you sure?' }, class: "btn-link-clear btn btn-link" %>
              </div>



          </div>

      <% end %>
    <% end %>
    </div>

  </div>
</div>

app/views/items/new.html.erb
<div class="col-md-6 col-md-offset-3">
  <h1>Add a New Item</h1>
  <%= bootstrap_form_for @item, :multipart => true do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

      <%= f.text_field :name, layout: :default, class: "form-control" %>

      <%= f.file_field :image, inline: true %> <br>
      <%= f.text_field :image_url, label: "Upload image from URL . . . ", layout: :inline %>

    <%= submit_tag "Add Item", class: "btn btn-large btn-primary", layout: :default %>
  <% end %>
</div>