config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :loans

  get 'authentications/index'

  resources :items

  resources :users
  resources :borrowers

  resources :sessions, only: [:new, :create, :destroy]

  resources :authentications

  # Login information
  match '/register', to: "users#new", via: 'get'
  match '/login', to: 'sessions#new', via: 'get'
  match '/logout', to: 'sessions#destroy', via: 'delete'

  # Login Information
  #match '/settings/user'

  # OmniAuth Routes
  match 'auth/:provider/callback', to: 'authentications#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]

  root :to => "visitors#index"

  mount Sidekiq::Web, at: "/sidekiq"

end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'WhoBorrowed', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
        <%= render 'layouts/navigation_links' %>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<ul class="nav navbar-nav">
<% if signed_in? %>
  <li><%= link_to "Dashboard", '#' %></li>
  <li><%= link_to "Inventory", items_path %></li>
  <li><%= link_to "Loans", '#' %></li>
  <li><%= link_to "Borrowers", '#' %></li>


<% end %>
</ul>


<ul class="nav navbar-nav navbar-right">
  <% if signed_in? %>
    <li><%= link_to current_user.username, "#" %></li>
    <li><%= link_to "Social Accounts", authentications_path %></li>
    <li><%= link_to "Logout", logout_path, method: 'delete' %>
  <% else %>
    <li class="pull-right"><%= link_to 'Register', register_path %></li>
    <li class="pull-right"><%= link_to "Login", login_path %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Who Borrowed" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Who Borrowed" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>